export const toolDefinitions = [
  { id: 'select', label: 'Sel', command: 'select mode tap', key: 'Space' },
  { id: 'node', label: 'Node', command: 'input ,', key: ',' },
  { id: 'line', label: 'Line', command: 'line', key: 'L' },
  { id: 'rect', label: 'Rect', command: 'rectangle', key: 'A' },
  { id: 'poly', label: 'Poly', command: 'input poly', key: 'P' },
  { id: 'circle', label: 'Cir', command: 'gen cir seg 36', key: 'C' },
  { id: 'text', label: 'Text', command: 'input text', key: 'T' },
  { id: 'move', label: 'Move', command: 'move from point to point', key: 'M' },
  { id: 'measure', label: 'Dim', command: 'distance from point to point', key: 'D' },
  { id: 'extrude', label: 'Push', command: 'extrude selected z 10', key: 'E' },
  { id: 'offset', label: 'Off', command: 'offset selected 1', key: 'O' },
  { id: 'repeat', label: 'Rep', command: 'rep n 3 x', key: 'R' },
  { id: 'surface', label: 'Surf', command: 'surface from selected', key: 'S' },
  { id: 'zoomin', label: 'Z+', command: 'zoom in', key: '+' },
  { id: 'zoomout', label: 'Z-', command: 'zoom out', key: '-' },
  { id: 'zoombox', label: 'ZBox', command: 'zoom box', key: 'B' },
  { id: 'camera', label: 'Cam', command: 'pv from . to .', key: 'V' },
  { id: 'nearest', label: 'Near', command: 'snap nearest node', key: 'F' },
  { id: 'grid', label: 'Grid', command: 'snap grid intersection', key: 'G' },
  { id: 'flatten', label: 'Flat', command: 'merge line to 0', key: 'Alt+F' },
  { id: 'box', label: 'Box', command: 'select box', key: 'Shift+B' },
];

export const viewDefinitions = [
  { id: 'top', label: 'Top', command: 'view plan' },
  { id: 'north', label: 'N', command: 'view nelev' },
  { id: 'south', label: 'S', command: 'view south' },
  { id: 'east', label: 'E', command: 'view east' },
  { id: 'west', label: 'W', command: 'view west' },
  { id: 'axon', label: 'Axon', command: 'view 3d' },
];

export const menuCommands = {
  file: [
    ['Home', 'home'],
    ['New', 'file new'],
    ['Open', 'file open'],
    ['Save', 'file save'],
    ['Save As', 'file save as'],
    ['Share Link', 'share'],
    ['Download Model', 'download model'],
    ['Export JSON', 'file export json'],
  ],
  edit: [
    ['Select All', 'select all'],
    ['Clear Selection', 'select none'],
    ['Delete Line', 'delete line by click'],
    ['Delete Poly', 'delete poly by click'],
    ['Extrude', 'extrude selected z 10'],
    ['Flatten to Z0', 'merge line to 0'],
  ],
  view: viewDefinitions.map(view => [view.label, view.command]),
  draw: [
    ['Line', 'line'],
    ['Polyline', 'input poly'],
    ['Rectangle', 'rectangle'],
    ['Polygon', 'polygon sides 6'],
    ['Circle 36', 'gen cir seg 36'],
    ['Arc', 'arc start mid end'],
    ['Text', 'input text'],
  ],
  model: [
    ['Extrude Solid', 'extrude selected z 10'],
    ['Surface From Selected', 'surface from selected'],
    ['Mesh From Selected', 'mesh from selected'],
    ['Flatten Z0', 'merge line to 0'],
  ],
  tools: [
    ['Move', 'move from point to point'],
    ['Measure', 'distance from point to point'],
    ['Extrude', 'extrude selected z 10'],
    ['Repeat N', 'rep n 3 x'],
    ['Rotate X', 'rotate x 90'],
    ['Rotate Y', 'rotate y 90'],
    ['Rotate Z', 'rotate z 90'],
    ['Zoom In', 'zoom in'],
    ['Zoom Out', 'zoom out'],
    ['Zoom Box', 'zoom box'],
    ['Zoom Extents', 'zoom extents'],
    ['Perspective Camera', 'pv from . to .'],
    ['Offset', 'offset selected 1'],
    ['Trim', 'trim selected'],
    ['Join', 'join selected'],
    ['Box In', 'select in box'],
    ['Box Crossing', 'select out box'],
  ],
  export: [
    ['Export JSON', 'file export json'],
    ['Export DXF', 'export dxf'],
    ['Export SVG', 'export svg'],
    ['Export STL', 'export stl'],
    ['Export OBJ', 'export obj'],
  ],
  window: [
    ['Entity Tray', 'tray entity'],
    ['Layers Tray', 'tray layers'],
    ['Outliner Tray', 'tray outliner'],
    ['Scenes Tray', 'tray scenes'],
    ['App Settings', 'app settings'],
    ['AI Assistant', 'ai assistant'],
    ['Visualization', 'visualization panel'],
    ['Add Location', 'add location'],
  ],
  system: [
    ['System README', 'system readme'],
    ['Roadmap', 'system roadmap'],
    ['Code Tightening', 'system code tightening'],
    ['Guidelines', 'system guidelines'],
    ['Architecture', 'system architecture'],
    ['Geometry Rules', 'system geometry rules'],
    ['Module System', 'system module system'],
    ['MCP Contracts', 'system mcp servers'],
  ],
};

export const state = {
  project: {
    name: 'Untitled DrawVision Model',
    savedAt: null,
    dirty: false,
    storageKey: 'drawvision.currentModel',
  },
  settings: {
    autosave: true,
    autosaveInterval: 30,
    template: 'architectural',
    axisX: '#e45d5d',
    axisY: '#5aa8ff',
    inference: '#e1b955',
    highContrast: false,
    inputDevice: 'mouse',
    invertZoom: false,
    invertPan: false,
    zoomSensitivity: 1,
    panSensitivity: 1,
    orbitSensitivity: 1,
    memoryWarnings: true,
    memoryThreshold: 80,
    clearUndoOnOptimize: true,
  },
  geolocation: {
    query: '',
    latitude: null,
    longitude: null,
    trueNorth: 0,
    importType: 'flat-site',
    mapTexture: 'street-map',
    terrainMesh: false,
    buildings3d: false,
  },
  env: {
    units: 'architectural',
    modelUnit: "1 unit = 1'-0\"",
    paperScale: '1:1',
    virtualScale: '1:100',
    scale: 'paper 1:1 / virtual 1:100',
    textSpace: 'paper',
    gridFeet: 20,
    gridSnapFeet: 1,
    gridOrigin: { x: 80, y: 70 },
    pxPerFoot: 20,
  },
  ui: {
    activeTool: 'select',
    activeView: 'top',
    activeTray: 'entity',
    axisLock: null,
    selectionMode: 'tap',
    graphicSelector: false,
    snapMode: 'grid-intersection',
    snapNearestNode: false,
    snapGridIntersection: true,
    hiddenLineDisplay: false,
    showNodes: false,
    status: 'Paper 1:1 / Virtual 1:100',
    measurement: 'Ready',
    commandHistory: ['DrawVision ready.'],
    searchResults: [],
    systemPanel: 'readme',
  },
  undoStack: [],
  pending: {
    firstPoint: null,
    polyPoints: [],
    circleCenter: null,
    rectStart: null,
    boxStart: null,
    zoomBoxStart: null,
    cameraEye: null,
    cursorPoint: [0, 0, 0],
  },
  camera: {
    eye: null,
    target: null,
    mode: 'orthographic',
  },
  viewBox: [0, 0, 720, 540],
  circle: {
    segments: 36,
    qualifier: 'radius',
    fixedRadius: null,
  },
  text: {
    value: 'Text',
  },
  selectedIds: ['wall_north'],
  groups: [],
  activeGroupId: null,
  materials: [
    { id: 'concrete', name: 'Concrete', fill: 'rgba(214,170,66,.22)', stroke: '#d6aa42' },
    { id: 'glass', name: 'Glass', fill: 'rgba(90,168,255,.18)', stroke: '#5aa8ff' },
    { id: 'mass-timber', name: 'Mass timber', fill: 'rgba(195,124,72,.26)', stroke: '#c37c48' },
    { id: 'structure', name: 'Structure', fill: 'rgba(228,93,93,.18)', stroke: '#e45d5d' },
    { id: 'site', name: 'Site', fill: 'rgba(36,180,126,.16)', stroke: '#24b47e' },
  ],
  layers: [
    { id: 'walls', name: 'Walls', color: '#d95c4f', visible: true, locked: false },
    { id: 'floor', name: 'Floor', color: '#d6aa42', visible: true, locked: false },
    { id: 'guides', name: 'Guides', color: '#5aa8ff', visible: true, locked: false },
    { id: 'notes', name: 'Notes', color: '#f1f4f7', visible: true, locked: false },
  ],
  objects: [
    { id: 'floor_loop', type: 'poly', layer: 'floor', points: [[3,16,0], [17,16,0], [17,4,0], [3,4,0]], fill: 'rgba(214,170,66,.22)', stroke: '#d6aa42', weight: 2, closed: true, attrs: { material: 'concrete' } },
    { id: 'wall_north', type: 'line', layer: 'walls', points: [[3,16,0], [17,16,0]], stroke: '#d95c4f', weight: 5, attrs: { height: '10' } },
    { id: 'wall_east', type: 'line', layer: 'walls', points: [[17,16,0], [17,4,0]], stroke: '#d95c4f', weight: 5, attrs: { height: '10' } },
    { id: 'circle_36', type: 'circle', layer: 'guides', center: [10,10,0], radius: 3.5, segments: 36, stroke: '#5aa8ff', weight: 2, attrs: { role: 'profile' } },
    { id: 'note_1', type: 'text', layer: 'notes', point: [2,2,0], text: '20 x 20 ft 1:1 grid', stroke: '#f1f4f7', attrs: {} },
    { id: 'massing_study', type: 'poly', layer: 'floor', points: [[5,13,0], [9,13,0], [9,9,0], [5,9,0]], fill: 'rgba(36,180,126,.16)', stroke: '#24b47e', weight: 2, closed: true, extrudeHeight: 6, attrs: { material: 'site', role: 'push-pull sample' } },
  ],
};